### ISSUE TITLE
divide the datasets

### ISSUE THREAD

**Issue by fgqile** [Shifts-Project/shifts#40]
HI! 
Can you divide the datasets into parts? When downloading the dataset, it always interrupts because of the network.

**Comment by gchesnokov** [comment]
Hi! Could you specify which dataset are you referring to?

**Comment by fgqile** [comment]
HI, thank you very much!
The speed is very low, as you can see.
![image](https://user-images.githubusercontent.com/64899378/163339359-045c142e-eec9-4836-a53a-deafd9e591ba.png)

 I want to download the vehicle motion dataset. can you give me a special link?  thanks.
